export interface Product {
  id: number
  name: string
  category: string
  price: number
  originalPrice?: number
  image: string
  images?: string[]
  badge?: string
  store: string
  rating: number
  reviews: number
  description: string
  features: string[]
  specs: Record<string, string>
}

export const productCatalog: Product[] = [
  {
    id: 1,
    name: "PlayStation 5 Digital Edition",
    category: "Tecnologia",
    price: 789.99,
    originalPrice: 850.0,
    image: "/playstation-5-console.png",
    images: ["/playstation-5-console.png"],
    badge: "-7%",
    store: "Tienda98",
    rating: 4.8,
    reviews: 1243,
    description: "La consola PlayStation 5 Digital Edition ofrece una experiencia de juego de nueva generacion con graficos impresionantes, tiempos de carga ultrarapidos gracias a su SSD personalizado, y el innovador control DualSense con retroalimentacion haptica.",
    features: [
      "SSD ultrarapido personalizado",
      "Retroalimentacion haptica DualSense",
      "Audio 3D Tempest",
      "Compatible con PS4 (digital)",
      "Resolucion hasta 4K a 120fps",
      "Ray Tracing en tiempo real",
    ],
    specs: {
      "CPU": "AMD Zen 2, 8 nucleos a 3.5 GHz",
      "GPU": "10.28 TFLOPS, 36 CUs a 2.23 GHz",
      "RAM": "16 GB GDDR6",
      "Almacenamiento": "825 GB SSD",
      "Resolucion": "Hasta 4K (8K ready)",
      "Conectividad": "Wi-Fi 6, Bluetooth 5.1, USB-A, USB-C",
    },
  },
  {
    id: 2,
    name: "Sony WH-CH520 Auriculares",
    category: "Tecnologia",
    price: 72.0,
    originalPrice: 85.0,
    image: "/wireless-headphones.png",
    images: ["/wireless-headphones.png"],
    badge: "-15%",
    store: "Tienda98",
    rating: 4.5,
    reviews: 876,
    description: "Auriculares inalambricos Sony WH-CH520 con sonido de alta calidad, diseno ligero y comodo, y hasta 50 horas de bateria.",
    features: [
      "Hasta 50 horas de bateria",
      "Conexion Bluetooth multipunto",
      "Diseno ultraligero",
      "Microfono incorporado",
      "Compatible con app Sony Headphones Connect",
      "Carga rapida USB-C",
    ],
    specs: {
      "Tipo": "On-ear inalambricos",
      "Driver": "30mm",
      "Frecuencia": "20Hz - 20kHz",
      "Bateria": "50 horas",
      "Peso": "147g",
      "Bluetooth": "5.2",
    },
  },
  {
    id: 3,
    name: "Smartwatch Amazfit GTS 4",
    category: "Tecnologia",
    price: 117.0,
    image: "/modern-smartwatch.png",
    images: ["/modern-smartwatch.png"],
    store: "Tienda98",
    rating: 4.3,
    reviews: 534,
    description: "Smartwatch Amazfit GTS 4 con pantalla AMOLED de 1.75 pulgadas, GPS integrado, monitoreo de salud avanzado y mas de 150 modos deportivos.",
    features: [
      "Pantalla AMOLED 1.75\"",
      "GPS integrado de doble banda",
      "Monitoreo de ritmo cardiaco 24/7",
      "Resistente al agua 5 ATM",
      "+150 modos deportivos",
      "Bateria de hasta 8 dias",
    ],
    specs: {
      "Pantalla": "1.75\" AMOLED",
      "Resolucion": "390 x 450 px",
      "Bateria": "300mAh, 8 dias",
      "Resistencia": "5 ATM",
      "Sensores": "BioTracker, acelerometro, giroscopio",
      "Conectividad": "Bluetooth 5.0, GPS",
    },
  },
  {
    id: 4,
    name: "Amazon Fire HD 10 Kids",
    category: "Tecnologia",
    price: 182.0,
    originalPrice: 199.0,
    image: "/tablet-kids.jpg",
    images: ["/tablet-kids.jpg"],
    badge: "-9%",
    store: "Tienda98",
    rating: 4.6,
    reviews: 2105,
    description: "Tablet Amazon Fire HD 10 Kids con pantalla Full HD de 10.1 pulgadas, funda protectora a prueba de ninos, 1 ano de Amazon Kids+ incluido.",
    features: [
      "Pantalla Full HD 10.1\"",
      "Funda protectora incluida",
      "1 ano de Amazon Kids+",
      "Control parental facil de usar",
      "Garantia de 2 anos",
      "32 GB almacenamiento expandible",
    ],
    specs: {
      "Pantalla": "10.1\" Full HD 1080p",
      "Procesador": "Octa-core 2.0 GHz",
      "RAM": "3 GB",
      "Almacenamiento": "32 GB (expandible 1TB)",
      "Bateria": "Hasta 12 horas",
      "Camara": "5 MP trasera, 2 MP frontal",
    },
  },
  {
    id: 5,
    name: "Samsung Galaxy Buds Pro",
    category: "Tecnologia",
    price: 149.99,
    originalPrice: 179.0,
    image: "/samsung-earbuds.jpg",
    images: ["/samsung-earbuds.jpg"],
    badge: "-16%",
    store: "Tienda98",
    rating: 4.4,
    reviews: 1562,
    description: "Samsung Galaxy Buds Pro con cancelacion de ruido activa inteligente, sonido envolvente 360 Audio, y resistencia al agua IPX7.",
    features: [
      "Cancelacion de ruido activa",
      "360 Audio inmersivo",
      "IPX7 resistente al agua",
      "Hasta 28h de bateria total",
      "Deteccion de voz",
      "Compatible con Galaxy Wearable",
    ],
    specs: {
      "Driver": "11mm woofer + 6.5mm tweeter",
      "ANC": "Si, 3 niveles",
      "Bateria": "5h (28h con estuche)",
      "Bluetooth": "5.0",
      "Resistencia": "IPX7",
      "Peso": "6.3g por auricular",
    },
  },
  {
    id: 6,
    name: "Nintendo Switch OLED",
    category: "Tecnologia",
    price: 349.0,
    image: "/nintendo-switch-console.png",
    images: ["/nintendo-switch-console.png"],
    store: "Tienda98",
    rating: 4.9,
    reviews: 3421,
    description: "Nintendo Switch modelo OLED con pantalla OLED vibrante de 7 pulgadas, base con puerto LAN, soporte ajustable de gran anchura, y 64 GB de almacenamiento interno.",
    features: [
      "Pantalla OLED de 7\"",
      "64 GB almacenamiento interno",
      "Puerto LAN en la base",
      "Soporte ajustable ancho",
      "Audio mejorado",
      "3 modos de juego",
    ],
    specs: {
      "Pantalla": "7\" OLED 1280x720",
      "CPU/GPU": "NVIDIA Tegra",
      "Almacenamiento": "64 GB (expandible)",
      "Bateria": "4.5 - 9 horas",
      "Peso": "420g (con Joy-Con)",
      "Conectividad": "Wi-Fi, Bluetooth 4.1, USB-C",
    },
  },
  {
    id: 7,
    name: "Apple iPad Air 5ta Gen",
    category: "Tecnologia",
    price: 599.0,
    originalPrice: 649.0,
    image: "/ipad-air.png",
    images: ["/ipad-air.png"],
    badge: "-8%",
    store: "Tienda98",
    rating: 4.7,
    reviews: 2876,
    description: "iPad Air de 5ta generacion con chip M1, pantalla Liquid Retina de 10.9 pulgadas, compatible con Apple Pencil y Magic Keyboard.",
    features: [
      "Chip Apple M1",
      "Pantalla Liquid Retina 10.9\"",
      "Compatible con Apple Pencil 2da gen",
      "Compatible con Magic Keyboard",
      "Touch ID integrado",
      "Camara frontal ultra gran angular 12 MP",
    ],
    specs: {
      "Chip": "Apple M1",
      "Pantalla": "10.9\" Liquid Retina",
      "Almacenamiento": "64 GB / 256 GB",
      "Camara": "12 MP trasera, 12 MP frontal",
      "Bateria": "Hasta 10 horas",
      "Conectividad": "Wi-Fi 6, Bluetooth 5.0, USB-C",
    },
  },
  {
    id: 8,
    name: "Logitech MX Master 3S",
    category: "Tecnologia",
    price: 99.99,
    originalPrice: 119.0,
    image: "/wireless-computer-mouse.png",
    images: ["/wireless-computer-mouse.png"],
    badge: "-16%",
    store: "Tienda98",
    rating: 4.6,
    reviews: 945,
    description: "Mouse ergonomico inalambrico Logitech MX Master 3S con sensor de 8000 DPI, scroll MagSpeed, y conectividad multi-dispositivo.",
    features: [
      "Sensor de 8000 DPI",
      "Scroll MagSpeed ultrarapido",
      "Conecta hasta 3 dispositivos",
      "USB-C de carga rapida",
      "Hasta 70 dias de bateria",
      "Compatible con Logi Options+",
    ],
    specs: {
      "Sensor": "Darkfield 8000 DPI",
      "Botones": "7 programables",
      "Bateria": "Hasta 70 dias",
      "Conectividad": "Bluetooth, USB Logi Bolt",
      "Peso": "141g",
      "Compatibilidad": "Windows, macOS, Linux, iPadOS",
    },
  },
  {
    id: 9,
    name: "Zapatillas Nike Air Max",
    category: "Moda y Accesorios",
    price: 149.99,
    image: "/nike-sneakers.jpg",
    store: "Fashion Store",
    rating: 4.5,
    reviews: 890,
    description: "Zapatillas Nike Air Max con diseno moderno y comodidad superior para el dia a dia.",
    features: ["Amortiguacion Air Max", "Diseno moderno", "Suela de goma duradera", "Malla transpirable"],
    specs: { "Material": "Malla/Sintetico", "Suela": "Goma", "Tipo": "Casual/Deportivo" },
  },
  {
    id: 10,
    name: "Camiseta Deportiva Adidas",
    category: "Deportes",
    price: 39.99,
    image: "/sports-tshirt.png",
    store: "DeportesEC",
    rating: 4.3,
    reviews: 456,
    description: "Camiseta deportiva Adidas con tecnologia Climalite para mantenerte seco y comodo.",
    features: ["Tecnologia Climalite", "Tejido transpirable", "Diseno deportivo", "Lavable a maquina"],
    specs: { "Material": "Poliester 100%", "Tecnologia": "Climalite", "Tipo": "Deportiva" },
  },
  {
    id: 11,
    name: "Laptop HP 15.6\" Core i5",
    category: "Tecnologia",
    price: 899.99,
    image: "/modern-laptop-computer.jpg",
    store: "TechStore Ecuador",
    rating: 4.6,
    reviews: 1234,
    description: "Laptop HP con procesador Intel Core i5, pantalla de 15.6 pulgadas, ideal para trabajo y entretenimiento.",
    features: ["Intel Core i5", "8 GB RAM", "256 GB SSD", "Pantalla 15.6\" Full HD", "Windows 11"],
    specs: { "Procesador": "Intel Core i5-1235U", "RAM": "8 GB DDR4", "Almacenamiento": "256 GB SSD", "Pantalla": "15.6\" FHD" },
  },
  {
    id: 12,
    name: "iPhone 15 Pro Max",
    category: "Tecnologia",
    price: 1299.99,
    image: "/modern-smartphone.png",
    store: "MovilShop",
    rating: 4.9,
    reviews: 5432,
    description: "iPhone 15 Pro Max con chip A17 Pro, sistema de camaras pro y diseno de titanio.",
    features: ["Chip A17 Pro", "Camara 48MP", "Titanio", "USB-C", "Action Button"],
    specs: { "Chip": "A17 Pro", "Pantalla": "6.7\" OLED", "Almacenamiento": "256 GB", "Camara": "48 MP + 12 MP + 12 MP" },
  },
  {
    id: 13,
    name: "Smart TV Samsung 55\"",
    category: "Tecnologia",
    price: 699.99,
    image: "/modern-smart-tv.jpg",
    store: "ElectroHogar",
    rating: 4.5,
    reviews: 2100,
    description: "Smart TV Samsung de 55 pulgadas con resolucion 4K UHD y sistema operativo Tizen.",
    features: ["4K UHD", "Tizen OS", "HDR10+", "Bluetooth", "Control por voz"],
    specs: { "Pantalla": "55\" LED 4K", "Resolucion": "3840 x 2160", "Sistema": "Tizen", "HDMI": "3 puertos" },
  },
  {
    id: 14,
    name: "Audifonos Sony Bluetooth",
    category: "Tecnologia",
    price: 179.99,
    image: "/wireless-headphones.png",
    store: "AudioPro",
    rating: 4.7,
    reviews: 1800,
    description: "Audifonos Sony inalambricos con cancelacion de ruido y sonido de alta fidelidad.",
    features: ["Cancelacion de ruido", "30h de bateria", "Hi-Res Audio", "Bluetooth 5.2"],
    specs: { "Tipo": "Over-ear", "Bateria": "30 horas", "Bluetooth": "5.2", "ANC": "Si" },
  },
]

export function searchProducts(query: string): Product[] {
  if (!query.trim()) return []
  const q = query.toLowerCase().trim()
  return productCatalog.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.category.toLowerCase().includes(q) ||
      p.store.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q)
  )
}
